Remove incompatible codesign performance improvement when on Tahoe
Summary:
On macOS Tahoe our performance improvement is no longer valid:
> error: signing with only SHA1 not allowed. Please remove `sha1` from the `--digest-algorithm` code signing flag.`

More details here: https://fb.workplace.com/groups/iosdevxadhoc/permalink/1752393665641905/

See https://www.internalfb.com/buck2/cc7e25c2-6d32-4a97-bf8a-5fc14e515a97 and https://www.internalfb.com/buck2/2bb1f909-18d6-4ba6-a8ab-ca79f24dc185 for sample invocations that hit this on macOS Tahoe (e.g. Darwin kernel version 25.0.0).

Let's remove it when we are on Tahoe to keep our bundling and codesigning working on Tahoe.

Reviewed By: milend, luizperes

Differential Revision: D80192955

fbshipit-source-id: b7b97c6d99d836163c11dee2fad9c7ae358f2d5a