Fix No MetadataExtensions instances found in the classpath.
Summary:
Repro: `buck test --prefer-remote fbsource//fbandroid/instrumentation_tests/com/facebook/stella/assistant/settings/providers/view/publicshare:publicshare -- --exact 'fbsource//fbandroid/instrumentation_tests/com/facebook/stella/assistant/settings/providers/view/publicshare:publicshare - autoLockDisabled[mode=DARK]` `(com.facebook.stella.assistant.settings.providers.view.publicshare.PublicShareScreenScreenshotTest)'`

error: `java.lang.IllegalStateException: No MetadataExtensions instances found in the classpath. Please ensure that the META-INF/services/ is not stripped from your application and that the Java virtual machine is not running under a security manager`

Full Error https://www.internalfb.com/intern/testinfra/diagnostics/3940649987157558.281475153277403.1759170369/

Investigation: this is due to "META-INF/services/kotlin.reflect.jvm.internal.impl.km.internal.extensions.MetadataExtensions",, not allowlisted in ApkJarBuilder.java

Reviewed By: IanChilds

Differential Revision: D83542016

fbshipit-source-id: b58af7e3c23e7d08f12073b1965e6bd4343d4f95