Include index store data in apple_test targets
Summary:
Previously we couldn't use build_index_store.bxl to build an index store for test targets, because it relies on accessing the `IndexStoreInfo` provider.

```
$ buck2 run prelude//ide_integrations/apple/build_index:build_index_store -- -t 'waios//Tests/Snapshot/SnapshotBusinessDiscoveryTests:SnapshotBusinessDiscoveryTests' -d '/tmp/foobar'
...
error: provider collection does not have a key `IndexStoreInfo`, available keys are: [`DefaultInfo`, `ExternalRunnerTestInfo`, `XcodeDataInfo`, `CxxCompilationDbInfo`, `AppleBundleManifestInfo`]
  --> fbcode/buck2/prelude/ide_integrations/apple/build_index/swift_index_store.bxl:36:28
   |
36 |         index_store_info = analysis_res.providers()[IndexStoreInfo]
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Pass the `IndexStoreInfo` provider through to apple_test targets, following the pattern in D38833535.

Reviewed By: IanChilds

Differential Revision: D79720726

fbshipit-source-id: 8fe1e48ab72981fff8364bd765400da9fe3f73de