Disable sanitizer in buildscript C/C++ compilers
Summary:
Without this, some ARVR build modes were linking a combination of sanitized and unsanitized objects, which does not work.

```lang=log,counterexample
Action failed: fbsource//third-party/rust/vendor/aws-lc-sys:0.37-build-script-main-run (buildscript)
thread 'main' (466427) panicked at third-party/rust/vendor/aws-lc-sys-0.37.1/builder/cc_builder.rs:702:9:
COMPILER: buck-out/v2/art/fbsource/9c8fa941126c444f/third-party/rust/vendor/aws-lc-sys/__0.37-build-script-main-run__/__cc_shim.sh
ARGS: ["-Wall", "-Wextra", "buck-out/v2/art/fbsource/9c8fa941126c444f/third-party/rust/vendor/aws-lc-sys/__0.37-build-script-main-run__/cwd/aws-lc/tests/compiler_features_tests/memcmp_invalid_stripped_check.c", "-Wno-unused-parameter", "-o", "buck-out/v2/art/fbsource/9c8fa941126c444f/third-party/rust/vendor/aws-lc-sys/__0.37-build-script-main-run__/OUT_DIR/memcmp_invalid_stripped_check"]
ERROR: ld.lld: error: undefined symbol: typeinfo for __cxxabiv1::__si_class_type_info
>>> referenced by ubsan_type_hash_itanium.cpp.o:(findBaseAtOffset(__cxxabiv1::__class_type_info const*, long)) in archive arvr/third-party/toolchains/platform010/build/llvm-fb/15/lib/clang/15.0.7/lib/x86_64-redhat-linux-gnu/libclang_rt.asan_cxx.a
>>> referenced by ubsan_type_hash_itanium.cpp.o:(isDerivedFromAtOffset(__cxxabiv1::__class_type_info const*, __cxxabiv1::__class_type_info const*, long)) in archive arvr/third-party/toolchains/platform010/build/llvm-fb/15/lib/clang/15.0.7/lib/x86_64-redhat-linux-gnu/libclang_rt.asan_cxx.a

ld.lld: error: undefined symbol: typeinfo for __cxxabiv1::__class_type_info
>>> referenced by ubsan_type_hash_itanium.cpp.o:(findBaseAtOffset(__cxxabiv1::__class_type_info const*, long)) in archive arvr/third-party/toolchains/platform010/build/llvm-fb/15/lib/clang/15.0.7/lib/x86_64-redhat-linux-gnu/libclang_rt.asan_cxx.a
>>> referenced by ubsan_type_hash_itanium.cpp.o:(isDerivedFromAtOffset(__cxxabiv1::__class_type_info const*, __cxxabiv1::__class_type_info const*, long)) in archive arvr/third-party/toolchains/platform010/build/llvm-fb/15/lib/clang/15.0.7/lib/x86_64-redhat-linux-gnu/libclang_rt.asan_cxx.a
>>> referenced by ubsan_type_hash_itanium.cpp.o:(isDerivedFromAtOffset(__cxxabiv1::__class_type_info const*, __cxxabiv1::__class_type_info const*, long)) in archive arvr/third-party/toolchains/platform010/build/llvm-fb/15/lib/clang/15.0.7/lib/x86_64-redhat-linux-gnu/libclang_rt.asan_cxx.a
>>> referenced 1 more times

ld.lld: error: undefined symbol: __dynamic_cast
>>> referenced by ubsan_type_hash_itanium.cpp.o:(findBaseAtOffset(__cxxabiv1::__class_type_info const*, long)) in archive arvr/third-party/toolchains/platform010/build/llvm-fb/15/lib/clang/15.0.7/lib/x86_64-redhat-linux-gnu/libclang_rt.asan_cxx.a
>>> referenced by ubsan_type_hash_itanium.cpp.o:(findBaseAtOffset(__cxxabiv1::__class_type_info const*, long)) in archive arvr/third-party/toolchains/platform010/build/llvm-fb/15/lib/clang/15.0.7/lib/x86_64-redhat-linux-gnu/libclang_rt.asan_cxx.a
>>> referenced by ubsan_type_hash_itanium.cpp.o:(isDerivedFromAtOffset(__cxxabiv1::__class_type_info const*, __cxxabiv1::__class_type_info const*, long)) in archive arvr/third-party/toolchains/platform010/build/llvm-fb/15/lib/clang/15.0.7/lib/x86_64-redhat-linux-gnu/libclang_rt.asan_cxx.a
>>> referenced 2 more times

ld.lld: error: undefined symbol: typeinfo for __cxxabiv1::__vmi_class_type_info
>>> referenced by ubsan_type_hash_itanium.cpp.o:(findBaseAtOffset(__cxxabiv1::__class_type_info const*, long)) in archive arvr/third-party/toolchains/platform010/build/llvm-fb/15/lib/clang/15.0.7/lib/x86_64-redhat-linux-gnu/libclang_rt.asan_cxx.a
>>> referenced by ubsan_type_hash_itanium.cpp.o:(isDerivedFromAtOffset(__cxxabiv1::__class_type_info const*, __cxxabiv1::__class_type_info const*, long)) in archive arvr/third-party/toolchains/platform010/build/llvm-fb/15/lib/clang/15.0.7/lib/x86_64-redhat-linux-gnu/libclang_rt.asan_cxx.a

ld.lld: error: undefined symbol: typeinfo for std::type_info
>>> referenced by ubsan_type_hash_itanium.cpp.o:(__ubsan::checkDynamicType(void*, void*, unsigned long)) in archive arvr/third-party/toolchains/platform010/build/llvm-fb/15/lib/clang/15.0.7/lib/x86_64-redhat-linux-gnu/libclang_rt.asan_cxx.a
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
OUTPUT: Failed to compile memcmp_invalid_stripped_check

stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <build_script_main::cc_builder::CcBuilder>::build_library
   3: <build_script_main::cc_builder::CcBuilder as build_script_main::Builder>::build
   4: build_script_main::main
```

Reviewed By: capickett

Differential Revision: D97328488

fbshipit-source-id: 6d6b18ab3fce20dfc300a7aadd5f81af9246c9eb