Back out "Differentiate -Cmetadata by configured target"
Summary:
D73334841 is breaking many tests, seemingly only in Monarch. I am able to reproduce one of the failures with `buck2 test fbcode//monarch/torch-sys:torch-sys-unittest -- --exact 'monarch/torch-sys:torch-sys-unittest - ivalue::tests::test_py_object_roundtrip_string'`.

```lang=text,counterexample
✗ Fail: monarch/torch-sys:torch-sys-unittest - ivalue::tests::test_py_object_roundtrip_string (20.4s)

thread 'ivalue::tests::test_py_object_roundtrip_string' panicked at fbcode/monarch/torch-sys/src/ivalue.rs:524:5:
called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'ImportError'>, value: ImportError('buck-out/v2/gen/fbcode/bea2be68e3f66b96/monarch/torch-sys/__torch-sys-py-deps__/torch-sys-py-deps#link-tree/libconfigerator_structs_data_access_policies_if_default_purposes-rust.so: undefined symbol: _RINvNtCsaSF5QmJeK2h_4core3ptr13drop_in_placeNtNtCs5w8a74bqfSY_5alloc6string6StringECs4nKITuYkYpg_8num_cpus'), traceback: Some(<traceback object at 0x7fa8c8c2bc00>) }
stack backtrace:
   0: rust_begin_unwind
             at xplat/rust/toolchain/sysroot/1.86.0/library/std/src/panicking.rs:695:5
   1: core::panicking::panic_fmt
             at xplat/rust/toolchain/sysroot/1.86.0/library/core/src/panicking.rs:75:14
   2: core::result::unwrap_failed
             at xplat/rust/toolchain/sysroot/1.86.0/library/core/src/result.rs:1704:5
   3: torch_sys::ivalue::tests::test_py_object_roundtrip_string
             at xplat/rust/toolchain/sysroot/1.86.0/library/core/src/result.rs:1109:23
   4: torch_sys::ivalue::tests::test_py_object_roundtrip_string::{closure#0}
             at fbcode/monarch/torch-sys/src/ivalue.rs:493:73
   5: <torch_sys::ivalue::tests::test_py_object_roundtrip_string::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at xplat/rust/toolchain/sysroot/1.86.0/library/core/src/ops/function.rs:250:5
```

And with `buck2 test fbcode//mode/dev-nosan fbcode//monarch/torch-sys:torch-sys-unittest -- --exact 'monarch/torch-sys:torch-sys-unittest - ivalue::tests::test_py_object_roundtrip_string'`:

```lang=text,counterexample
✗ Fail: monarch/torch-sys:torch-sys-unittest - ivalue::tests::test_py_object_roundtrip_string (3.5s)

thread 'ivalue::tests::test_py_object_roundtrip_string' panicked at fbcode/monarch/torch-sys/src/ivalue.rs:524:5:
called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'ImportError'>, value: ImportError('buck-out/v2/gen/fbcode/7da856849407c069/monarch/torch-sys/__torch-sys-py-deps__/torch-sys-py-deps#link-tree/libconfigerator_structs_data_access_policies_if_default_purposes-rust.so: undefined symbol: _RINvNtCshIJNIolSDov_4core3ptr13drop_in_placeNtNtCsbFoPppxOVSO_5alloc6string6StringECs1nDzSvvwlHo_6anyhow'), traceback: Some(<traceback object at 0x7f66a3c9fbc0>) }
stack backtrace:
   0: rust_begin_unwind
             at xplat/rust/toolchain/sysroot/1.86.0/library/std/src/panicking.rs:695:5
   1: core::panicking::panic_fmt
             at xplat/rust/toolchain/sysroot/1.86.0/library/core/src/panicking.rs:75:14
   2: core::result::unwrap_failed
             at xplat/rust/toolchain/sysroot/1.86.0/library/core/src/result.rs:1704:5
   3: torch_sys::ivalue::tests::test_py_object_roundtrip_string
             at xplat/rust/toolchain/sysroot/1.86.0/library/core/src/result.rs:1109:23
   4: torch_sys::ivalue::tests::test_py_object_roundtrip_string::{closure#0}
             at fbcode/monarch/torch-sys/src/ivalue.rs:493:73
   5: <torch_sys::ivalue::tests::test_py_object_roundtrip_string::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at xplat/rust/toolchain/sysroot/1.86.0/library/core/src/ops/function.rs:250:5
```

I need to investigate further why this target appears to be linking 2 different configurations of some dependency and expecting that they provide interchangeable symbols.

Reviewed By: JakobDegen

Differential Revision: D73400841

fbshipit-source-id: d600207241b91ce111c428d76bc1752a82f4e048