Fix show_headers dep file processing not showing errors.
Summary:
When using the `show_headers` dep file parsing mode (generally used with clang), a script `show_headers_to_dep_file.py` is invoked behind the scenes in order to convert the output of clang's `--show-headers` argument into a dep file.  When the invocation of `clang --show-headers` fails for any reason, the script completely swallows the output and it does not propagate up to the user, which results in the user having no feedback about the cause of the error.  Moreover, since this action runs before the action which runs the true compilation, a failure on this action terminates the build with no feedback, and no other subsequent steps run to fill in the missing pieces, so the user is just left with no information.

This is an extremely common use case, since something as simple as forgetting to list a header in the `headers` or `exported_headers` attribute of a `cxx_library` will trigger it.

The root cause of this bug is that the script would only parse the output of the compiler if the returncode indicated that the process succeeded.  Ironically, the function to parse the output already handled the case of printing error lines back to stdout, it just wasn't called when there was an error.

Here is some sample output of buck2 running an action remotely with and without this PR:

with PR:
```
$ buck2 build --target-platforms=internal//platforms:linux-x64 //Client/Core:Core[objects][src/Bitset.cpp.o]
Action failed: root//Client/Core:Core (cxx_compile src/Bitset.cpp)
Remote command returned non-zero exit code 1
stdout:
stderr:
In file included from Client/Core/src/Bitset.cpp:1:
In file included from Client/Core/include/Core/Bitset.h:3:
Client/Core/include/Core/Bit.h:81:10: fatal error: 'Bit.inl' file not found
#include "Bit.inl"
         ^~~~~~~~~
.. /usr/lib/llvm-12/bin/../include/c++/v1/string
1 error generated.
Build ID: a5eaf819-1a66-419d-8688-f602a39a126c
Network: (GRPC-SESSION-ID)
Jobs completed: 5. Time elapsed: 2.6s.
Cache hits: 0%. Commands: 1 (cached: 0, remote: 1, local: 0)
BUILD FAILED
Failed to build 'root//Client/Core:Core (internal//platforms:linux-x64#48291db568f0aab5)'
```

without PR:
```
$ buck2 build --target-platforms=internal//platforms:linux-x64 //Client/Core:Core[objects][src/Bitset.cpp.o]
Action failed: root//Client/Core:Core (cxx_compile src/Bitset.cpp)
Remote command returned non-zero exit code 1
stdout:
stderr:
Build ID: a5eaf819-1a66-419d-8688-f602a39a126c
Network: (GRPC-SESSION-ID)
Jobs completed: 5. Time elapsed: 2.6s.
Cache hits: 0%. Commands: 1 (cached: 0, remote: 1, local: 0)
BUILD FAILED
Failed to build 'root//Client/Core:Core (internal//platforms:linux-x64#48291db568f0aab5)'
```

X-link: https://github.com/facebook/buck2/pull/625

Reviewed By: lmvasquezg

Differential Revision: D56686585

Pulled By: JakobDegen

fbshipit-source-id: e974de25825f025260719723029b93e29d906a3c