disable macro sandbox in re workers
Summary:
When running remote actions that execute macros, we need to disable the sandbox used for the macro subprocesses, as otherwise actions fail with:
```
sandbox-exec: sandbox_apply: Operation not permitted
...
error: external macro implementation type 'SwiftMacros.TaskLocalMacro' could not be found for macro 'TaskLocal()'; '/paragon/pods/271232256/home/execution/0/f12ce3a57fb24d95822168472f00c630/work/buck-out/v2/gen/fbsource/5aecc2f8073dbfd1/xplat/toolchains/apple/__xcode_16.2.0_16c5032a-iphoneos-platform_genrule-actual__/unpacked/Developer/usr/bin/swift-plugin-server' produced malformed response
```

Reviewed By: drodriguez

Differential Revision: D70096317

fbshipit-source-id: a4b92f63eeeee6e335023257dac2dabb9099e377