Add -target arg to go compilation
Summary:
Similar to the previous diff D63752347, but for go, with the lack of a flag declaring darwin-ness (like `-target` or `-mmacosx-version-min=10.15`), seeing failures like:

```
gcc_darwin_arm64.c:16:10: fatal error: 'TargetConditionals.h' file not found
```
(T203867759)

or

```
gcc_darwin_amd64.c:34:9: error: call to undeclared function 'pthread_get_stacksize_np'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
```

This change calls get_target_sdk_version_flags() to get the `-target` flag so the go wrapper has the right set of clang flags.

Reviewed By: rmaz

Differential Revision: D64082279

fbshipit-source-id: be3e294a484dd3df1d1f8aafe379b1d464678010