Fix incremental bundling
Summary:
D55867562 added a new required field which means incremental bundling stopped working because it could no longer read the state:

```
2024-04-15 15:46:33,394 - __main__ - INFO - Will read incremental state from `buck-out/v2/gen/fbsource/9e81a6d4219943e9/fbobjc/buck2/samples/hello_world/__HelloWorldBundle__/incremental_state.json`. (main.py:478)
2024-04-15 15:46:33,395 - __main__ - ERROR - Failed to read incremental state (main.py:488)
Traceback (most recent call last):
  File "/Users/mgd/fbsource/buck-out/v2/gen/prelude/54bf3c7a3997dbfb/apple/tools/bundling/__assemble_bundle__/assemble_bundle#link-tree/apple/tools/bundling/main.py", line 486, in _read_incremental_state
    return parse_incremental_state(f)
  File "/Users/mgd/fbsource/buck-out/v2/gen/prelude/54bf3c7a3997dbfb/apple/tools/bundling/__assemble_bundle__/assemble_bundle#link-tree/apple/tools/bundling/incremental_state.py", line 152, in parse_incremental_state
    incremental_state = json.load(data, object_hook=_object_hook)
  File "/usr/local/fbcode/platform010/Python3.10.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/fbcode/platform010/Python3.10.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/local/fbcode/platform010/Python3.10.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/fbcode/platform010/Python3.10.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/Users/mgd/fbsource/buck-out/v2/gen/prelude/54bf3c7a3997dbfb/apple/tools/bundling/__assemble_bundle__/assemble_bundle#link-tree/apple/tools/bundling/incremental_state.py", line 132, in _object_hook
    return IncrementalState(**dict)
TypeError: IncrementalState.__init__() missing 1 required positional argument: 'codesign_arguments'
```

Reviewed By: blackm00n

Differential Revision: D56140638

fbshipit-source-id: d08fc7592a7104628bd75a330679432abd877b18