Fix build failures caused by missing shared library info
Summary:
Recent change (D39293464) caused a bunch of Pyre builds to fail the buck build step. The [error log](https://www.internalfb.com/intern/sandcastle/log/?instance_id=36028797801852936&step_id=36028805284897051&step_index=3&name=Run%20%60pyre%20check%60%20(fblearner%2Fflow%2Fprojects%2Fgrasp)#235-242) says:
```
error: Value `[None]` of type `list` does not match the type annotation `["SharedLibrariesTSet"]` for argument `shared_libraries`
```
Looking at this message, it suggests that the issue can be simply patched by removing the `None` element from the list when invoking that function, which is what I did in this diff.

Of course, the alternative is to dig into why exactly is it possible to produce a `None` element in the first place and patch things there. But I have very limited context on how native libraries are packaged, so I would probably need some pointers if it's more desirable to explore that direction.

Reviewed By: zsol, BrandonTheBuilder

Differential Revision: D39931186

fbshipit-source-id: ed388aba27714e6c5a6a08c02d37a4cd98147b76