Delete support for None values in doc_env
Summary:
{D49004163} already deleted support for this (unintentionally) so there hasn't been any use case for this.

Before that diff, `doc_env` used to be `dict[str, ArgLike | None]`.

https://www.internalfb.com/code/fbsource/[b93ac49e230d49bb62b17f8c114c80972c2d645f]/fbcode/buck2/prelude/decls/rust_rules.bzl?lines=242

while `env` is `dict[str, ArgLike]`.

https://www.internalfb.com/code/fbsource/[b93ac49e230d49bb62b17f8c114c80972c2d645f]/fbcode/buck2/prelude/decls/rust_common.bzl?lines=88

After that diff, `None` in `doc_env` was no longer accepted.

```
   error: Error coercing attribute `doc_env` of `fbcode//common/rust/shed/codegen_includer_proc_macro:_codegen_includer_proc_macro`
     --> fbcode/buck2/prelude/rust/rust_common.bzl:13:9
      |
   13 |         rust_rule(_workspaces = workspaces, **kwargs)
      |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |

1: Error coercing attribute `doc_env` of type `attrs.dict(attrs.string(), attrs.arg(), sorted=False, default={})`
2: Error coercing {"OUT_DIR": "$(location //common/rust/shed/codegen_includer_proc_macro/example:doc_test_out_dir)", "REPRO": None}
3: Error coercing None
4: Expected value of type `string`, got value with type `NoneType` (value was `None`)
```

This diff deletes related dead code. The code is from {D45633262}.

Reviewed By: zertosh

Differential Revision: D52764609

fbshipit-source-id: 90ca9199ce6ea5adfbe6bce6f0ec924c5315567f