Do not stub UL static class
Summary:
## Context
To fix an UL KSP related issue that after we changing stubgen to emit bytecode later in D71890539

```
com.facebook.buck.core.exceptions.HumanReadableException: Failed to execute isolated step <ksp2>
[ksp2] Couldn't resolve java wildcards! If the build fails, add ksp_disabled = True to your BUCK file.
[ksp2] Couldn't resolve java wildcards! If the build fails, add ksp_disabled = True to your BUCK file.

ksp.org.jetbrains.kotlin.utils.exceptions.KotlinIllegalArgumentExceptionWithAttachments: No classifier found
at ksp.org.jetbrains.kotlin.analysis.low.level.api.fir.providers.LLFirFirClassByPsiClassProvider.createFirClassFromFirProvider(LLFirFirClassByPsiClassProvider.kt:126)
at ksp.org.jetbrains.kotlin.analysis.low.level.api.fir.providers.LLFirFirClassByPsiClassProvider.getFirClass(LLFirFirClassByPsiClassProvider.kt:49)
at ksp.org.jetbrains.kotlin.analysis.api.fir.symbols.KaFirPsiJavaClassSymbol.firSymbol_delegate$lambda$23(KaFirPsiJavaClassSymbol.kt:126)
at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
at ksp.org.jetbrains.kotlin.analysis.api.fir.utils.ValidityAwareCachedValue.getValue-impl(ValidityAwareCachedValue.kt:21)
at ksp.org.jetbrains.kotlin.analysis.api.fir.symbols.KaFirPsiJavaClassSymbol.getFirSymbol(KaFirPsiJavaClassSymbol.kt:123)
at ksp.org.jetbrains.kotlin.analysis.api.fir.symbols.KaFirPsiJavaClassSymbol.getFirSymbol(KaFirPsiJavaClassSymbol.kt:43)
at ksp.org.jetbrains.kotlin.analysis.api.fir.utils.KtSymbolUtilsKt.getFirSymbol(ktSymbolUtils.kt:27)
at ksp.org.jetbrains.kotlin.analysis.api.fir.components.KaFirSymbolRelationProvider.hasParentSymbol(KaFirSymbolRelationProvider.kt:167)
at ksp.org.jetbrains.kotlin.analysis.api.fir.components.KaFirSymbolRelationProvider.getContainingDeclaration(KaFirSymbolRelationProvider.kt:76)
at ksp.org.jetbrains.kotlin.analysis.api.fir.components.KaFirSymbolRelationProvider.getContainingSymbol(KaFirSymbolRelationProvider.kt:70)
at ksp.org.jetbrains.kotlin.analysis.api.impl.base.KaBaseSession.getContainingSymbol(KaBaseSession.kt)
at com.google.devtools.ksp.impl.symbol.kotlin.AbstractKSDeclarationImpl$parent$2.invoke(AbstractKSDeclarationImpl.kt:109)
at com.google.devtools.ksp.impl.symbol.kotlin.AbstractKSDeclarationImpl$parent$2.invoke(AbstractKSDeclarationImpl.kt:107)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at com.google.devtools.ksp.impl.symbol.kotlin.AbstractKSDeclarationImpl.getParent(AbstractKSDeclarationImpl.kt:107)
at com.google.devtools.ksp.UtilsKt.getContainingFile(utils.kt:80)
at com.facebook.kotlin.ksp.kspadapter.KspAnnotatedElement$containingFile$2.invoke(KspAnnotatedElement.kt:33)
at com.facebook.kotlin.ksp.kspadapter.KspAnnotatedElement$containingFile$2.invoke(KspAnnotatedElement.kt:33)
at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
at com.facebook.kotlin.ksp.kspadapter.KspAnnotatedElement.getContainingFile(KspAnnotatedElement.kt:33)
at com.facebook.ultralight.injector.adapters.ksp.trees.KspTree$containingFile$2.invoke(KspTree.kt:29)
at com.facebook.ultralight.injector.adapters.ksp.trees.KspTree$containingFile$2.invoke(KspTree.kt:29)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at com.facebook.ultralight.injector.adapters.ksp.trees.KspTree.getContainingFile(KspTree.kt:29)
at com.facebook.ultralight.injector.adapters.ksp.trees.KspTree.access$getContainingFile(KspTree.kt:23)
at com.facebook.ultralight.injector.adapters.ksp.trees.KspTree$compilationUnitTree$2.invoke(KspTree.kt:32)
at com.facebook.ultralight.injector.adapters.ksp.trees.KspTree$compilationUnitTree$2.invoke(KspTree.kt:31)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at com.facebook.ultralight.injector.adapters.ksp.trees.KspTree.getCompilationUnitTree(KspTree.kt:31)
at com.facebook.ultralight.injector.adapters.ksp.trees.KspTreePath.<init>(KspTreePath.kt:11)
at com.facebook.ultralight.injector.adapters.ksp.trees.KspTreePath.<init>(KspTreePath.kt:13)
at com.facebook.ultralight.injector.adapters.ksp.trees.KspTrees.getPath(KspTrees.kt:52)
at com.facebook.ultralight.injector.adapters.ksp.KspTreesExtended.getPath(KspTreesExtended.kt:77)
at com.facebook.annotationprocessors.inject.InjectorProcessor.getElementsToProcess(InjectorProcessor.kt:316)
at com.facebook.annotationprocessors.inject.InjectorProcessor.processImpl(InjectorProcessor.kt:226)
at com.facebook.annotationprocessors.common.ProcessorBase.process(ProcessorBase.java:92)
at com.facebook.kotlin.ksp.kspadapter.JavaSymbolProcessorBase.processImpl(JavaSymbolProcessorBase.kt:73)
at com.facebook.kotlin.ksp.kspadapter.SymbolProcessorBase.process(SymbolProcessorBase.kt:56)
at com.google.devtools.ksp.impl.KotlinSymbolProcessing.execute(KotlinSymbolProcessing.kt:538)
at com.facebook.buck.jvm.kotlin.ksp.Ksp2Step.executeKsp2(Ksp2Step.kt:180)
at com.facebook.buck.jvm.kotlin.ksp.Ksp2Step.executeIsolatedStep(Ksp2Step.kt:72)
at com.facebook.buck.step.isolatedsteps.IsolatedStepsRunner.runStep(IsolatedStepsRunner.java:69)
at com.facebook.buck.step.isolatedsteps.IsolatedStepsRunner.execute(IsolatedStepsRunner.java:36)
at com.facebook.buck.step.isolatedsteps.IsolatedStepsRunner.executeWithDefaultExceptionHandling(IsolatedStepsRunner.java:56)
at com.facebook.buck.jvm.cd.CompilerDaemonRunner.execute(CompilerDaemonRunner.java:89)
at com.facebook.buck.jvm.cd.workertool.grpc.WorkerGrpcService.execute(WorkerGrpcService.java:50)
at com.facebook.buck.worker.model.WorkerGrpc$MethodHandlers.invoke(WorkerGrpc.java:288)
at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)

at com.facebook.buck.step.isolatedsteps.StepFailedException.getHumanReadableException(StepFailedException.java:70)
at com.facebook.buck.step.isolatedsteps.StepFailedException.createForFailingIsolatedStepWithExitCode(StepFailedException.java:54)
at com.facebook.buck.step.isolatedsteps.IsolatedStepsRunner.runStep(IsolatedStepsRunner.java:75)
at com.facebook.buck.step.isolatedsteps.IsolatedStepsRunner.execute(IsolatedStepsRunner.java:36)
at com.facebook.buck.step.isolatedsteps.IsolatedStepsRunner.executeWithDefaultExceptionHandling(IsolatedStepsRunner.java:56)
at com.facebook.buck.jvm.cd.CompilerDaemonRunner.execute(CompilerDaemonRunner.java:89)
at com.facebook.buck.jvm.cd.workertool.grpc.WorkerGrpcService.execute(WorkerGrpcService.java:50)
at com.facebook.buck.worker.model.WorkerGrpc$MethodHandlers.invoke(WorkerGrpc.java:288)
at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
```

## Issue

Sometime a target could have import for a UL static implementation class from same package.
e.g
`import com.instagram.feed.media.XDTMediaDict_should_show_locationStatic` [src](https://www.internalfb.com/code/fbsource/[f8aae87ab94f]/fbandroid/java/com/instagram/feed/media/ImmutablePandoMediaDict.kt?lines=461)

Previously we created stubs for these names, but when we changing to output bytecode and provide them as classpath, UL KSP will complain it can't find element from the file tree.

## Solution
We could keep those stubs as KTFiles for compilations, but since KSP will generate these classes, so we shouldn't need to stub these in first place.

Reviewed By: nghuiqin

Differential Revision: D72387277

fbshipit-source-id: 8ca1eb581b053b3f66b736c3ad7b772534d7ef34