Revert D75101064
Summary:
This diff reverts D75101064
This diff is breaking the VSCode type checker because it breaks `arc pyre check-changed-targets`

The original diff is causing `arc pyre check-changed-targets` to fail:
```
$ arc pyre check-changed-targets
2025-05-29T05:59:17.721-07:00  INFO arc_pyre_lib: Querying affected files from source control...
2025-05-29T05:59:17.933-07:00  INFO arc_pyre_lib: Found 1 existing changed Python files
2025-05-29T05:59:17.933-07:00  INFO arc_pyre_lib: Checking owning targets of existing changed Python files...
Traceback (most recent call last):
  File <builtin>, in <module>
  * fbcode/buck2/prelude/python/typecheck/batch_files.bxl:12, in _run_entry_point
      check_targets(ctx, targets)
error: Object of type `struct` has no attribute `keep_going`
  --> fbcode/buck2/prelude/python/typecheck/batch.bxl:76:5
   |
76 |       if ctx.cli_args.keep_going:
   |  _____^
77 | |         checked_targets = filter_and_get_typecheck_subtargets_keep_going(ctx, targets)
78 | |     else:
79 | |         checked_targets = filter_and_get_typecheck_subtargets(ctx, targets)
80 | |     artifacts = _check_targets_batched(ctx, checked_targets)
   | |_^
   |
Buck UI: https://www.internalfb.com/buck2/c09d4499-5849-406c-bd6a-7ea574247a72
Network: Up: 0B  Down: 0B
Command: bxl.
Time elapsed: 0.5s
BXL FAILED
2025-05-29T05:59:18.673-07:00 ERROR arc_pyre_lib: BXL invocation failed. Please check your Buck files and ensure the targets can be built.
2025-05-29T05:59:18.673-07:00 ERROR arc_pyre_lib: BXL command was terminated by `exit status: 3`
```

Which in turn causes the entire VS Code type checking to not run.

Reviewed By: thantos

Differential Revision: D75601214

fbshipit-source-id: 029a0feca8b9754638df9d346e9bdf51718ddc09