Provide both .(dyn_)hi and .(dyn_)o
Needed as we're building with `-dynamic-too` to resolve
```
backend/src/Culture/GitHub/Types.hs:8:1: error:
    Failed to load dynamic interface file for Culture.Display:
        Bad interface file:
	buck-out/v2/gen/root/c1257425379aabf2/backend/src/__backend_infra__/mod-static/Culture/Display.dyn_hi
	        buck-out/v2/gen/root/c1257425379aabf2/backend/src/__backend_infra__/mod-static/Culture/Display.dyn_hi:
		withBinaryFile: does not exist (No such file or
		directory)
```