norm path
Summary:
windows string needs to be normalized because

```
 File "D:\full-fbsource\buck-out\v2\gen\prelude\fcb34159a4c7b3ac\python\tools\__make_py_package_modules__\__make_py_package_modules__\make_py_package_modules.py", line 352, in <module>
    main()
  File "D:\full-fbsource\buck-out\v2\gen\prelude\fcb34159a4c7b3ac\python\tools\__make_py_package_modules__\__make_py_package_modules__\make_py_package_modules.py", line 348, in main
    create_modules_dir(args)
  File "D:\full-fbsource\buck-out\v2\gen\prelude\fcb34159a4c7b3ac\python\tools\__make_py_package_modules__\__make_py_package_modules__\make_py_package_modules.py", line 274, in create_modules_dir
    add_path_mapping(
  File "D:\full-fbsource\buck-out\v2\gen\prelude\fcb34159a4c7b3ac\python\tools\__make_py_package_modules__\__make_py_package_modules__\make_py_package_modules.py", line 208, in add_path_mapping
    link_path = os.path.relpath(
                ^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 783, in relpath
ValueError: path is on mount '\\\\?\\D:', start on mount 'D:'
```

the string  '\\\\?\\', just say that the path are long...

Reviewed By: QuantumManiac, halfacroissant

Differential Revision: D87559989

fbshipit-source-id: 6e86ce47ceacc5904ffb6b97a620ed18a2579226