Default to cxx toolchain `fbcode//buck2/platform:cxx-platform010-clang`
Summary:
Resolves the cxx toolchain to use `fbcode//buck2/platform:cxx-platform010-clang`, rather than relying on the `toolchains//:cxx` alaysis which is resolving to  `fbcode//buck2/platform/toolchain:no_toolchain`. This started happening after {D69234961}.

Going back to the previously used toolchain: `fbcode//buck2/platform:cxx-platform010-clang`

When `no_toolchain` is used, the script fails because the cxx_toolchain is `None`:

```
Command failed:
Traceback (most recent call last):
  File <builtin>, in <module>
  * fbcode/buck2/prelude/ide_integrations/visual_studio/gen_mode_configs.bxl:177, in _main
      _produce_proj_artifact_with_async_cxx_toolchain(bxl_ctx, actions, fbsource, o...
error: Object of type `NoneType` has no attribute `cxx_compiler_info`
   --> fbcode/buck2/prelude/ide_integrations/visual_studio/gen_mode_configs.bxl:119:77
    |
119 |     cxxflags_artifact, cxxflags_macro_artifacts = actions.write("cxxflags", cxx_toolchain.cxx_compiler_info.compiler_flags, allow_args = True)
    |                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |

BXL FAILED

```

Reviewed By: autozimu

Differential Revision: D71433113

fbshipit-source-id: f13f71b85b3fa6f8fb7a12c752ae0b7ff18d8161