fix prebuilt_ocaml_library includes.
Summary:
Fix suggested by Scott (https://fb.workplace.com/groups/buck2users/permalink/3337493289840362/).

The change kind of reverse D36310553.
The change for include_dir was not applied because it was causing build failures:
```
buck2 test fbcode//buck2/tests/targets/rules/ocaml/supercaml:
File "fbcode/buck2/tests/targets/rules/ocaml/supercaml/ocaml_expect_test.ml", line 10, characters 0-0:
Error: Unbound module Expect_test_collector
```

Reviewed By: ndmitchell, scottcao

Differential Revision: D42489278

fbshipit-source-id: 71e5ffc482130d11ded775546e77ffc0d2dd9219