Fix assembling ksp annotation processor classpath
Summary:
This was completely broken by D48267519, and wasn't noticed because we (incorrectly) don't have tests for non-KotlinCD (top of stack fixes that).

Previously, we would see:
```
[ianc@199751 fbsource]$ buck2 build fbcode//buck2/tests/targets/rules/kotlin/kotlin_library: -c kotlin.buck2_kotlincd_enabled=False
File changed: prelude//kotlin/kotlin_library.bzl
Error running analysis for `fbcode//buck2/tests/targets/rules/kotlin/kotlin_library:ksp_generates_new_class (ovr_config//platform/linux:x86_64-fbcode-platform010-clang#ff28bdc9faf03099)`

Caused by:
    Traceback (most recent call last):
      File <builtin>, in <module>
      * fbcode/buck2/prelude/kotlin/kotlin_library.bzl:261, in kotlin_library_impl
          java_providers = build_kotlin_library(ctx)
      * fbcode/buck2/prelude/kotlin/kotlin_library.bzl:305, in build_kotlin_library
          kotlinc_classes, kapt_generated_sources, ksp_generated_sources = _create_kotl...
    error: Object of type `list` has no attribute `deps`
       --> fbcode/buck2/prelude/kotlin/kotlin_library.bzl:161:9
        |
    161 |           if ksp_annotation_processor_properties.annotation_processors.deps:
        |  _________^
    162 | |             ksp_cmd.add(["--ksp_processor_jars"])
    163 | |             ksp_cmd.add(cmd_args(ksp_annotation_processor_properties.annotation_processors.deps.project_as_args("full_jar_args"), delimiter = ","))
    164 | |
    165 | |         ksp_cmd.add(["--ksp_classpath", classpath_args])
        | |_^
        |

Buck UI: https://www.internalfb.com/buck2/740ebf93-3505-40e1-bf83-662eca53e362
Network: Up: 0B  Down: 0B
Jobs completed: 3568. Time elapsed: 4.9s.
BUILD FAILED
```

So, construct the classpath correctly.

Reviewed By: jiawei-lyu

Differential Revision: D48949528

fbshipit-source-id: 0cb6d08d18035636d0d11688ccf194fcc1ac83e7