Disable incremental KSP for nullsafe
Summary:
### Context
KSP Incremental Processing is another promising area after KIC where we can apply incrementality techniques to improve build speed. However, enabling KSP Incremental Processing won't work out of the box—it requires certain support from annotation processors.

### This diff

When I enabled incremental KSP globally, I faced an issue with nullsafe.

```
error: Multiple artifacts and/or metadata files are declared at the same output location `action_metadata.json` declared at `fbcode/buck2/prelude/kotlin/kotlincd_jar_creator.bzl:531:5-548:6`.
--> fbcode/buck2/prelude/kotlin/kotlincd_jar_creator.bzl:531:5
|
531 | actions.run(
| _____^
532 | | args,
533 | | env = {
534 | | "BUCK_CLASSPATH": compiler,
535 | | "JAVACD_ABSOLUTE_PATHS_ARE_RELATIVE_TO_CWD": "1",
536 | | },
537 | | category = "{}kotlincd_jar".format(category_prefix),
538 | | identifier = actions_identifier,
539 | | dep_files = dep_files,
540 | | allow_dep_file_cache_upload = True,
541 | | allow_cache_upload = True,
542 | | exe = exe,
543 | | local_only = local_only,
544 | | low_pass_filter = False,
545 | | weight = 2,
546 | | error_handler = kotlin_toolchain.kotlin_error_handler,
547 | | **incremental_run_params
548 | | )
| |_____^
|
```

To resolve this issue, I created an override version of the Kotlin toolchain to prevent nullsafe from running as an incremental action. This approach allowed me to avoid duplicating information, but I am open to feedback on whether this is the best solution.

Reviewed By: NavidQar

Differential Revision: D79343968

fbshipit-source-id: 0fa4e95b1a44a43f00580c2d24cc3c9b0ffb9c73