Xplat Suffixing: handle arvr-rooted targets
Summary:
**Problem**

- arvr targets can depend on fbobjc targets which in turn depend on fb_xplat targets.
- in arvr mode, fb_xplat targets do not apply any target suffixing.
- This results in false positive xplat violations

```
$ buck2 audit providers fbsource//arvr/apps/hsr/demo:client_ipa fbsource//arvr/projects/hsr/mode/mac-arm/ios-simulator/development -c apple.meta_apple_library_validation=true --quiet
fbsource//arvr/apps/hsr/demo:client_ipa (cfg:iphoneos-arm64-iphonesimulator-no-san#cbc4c1f0584cf5e6): failed:
  Error running analysis for `fbsource//arvr/apps/hsr/demo:client_ipa (cfg:iphoneos-arm64-iphonesimulator-no-san#cbc4c1f0584cf5e6)`

  Caused by:
      0: Error running analysis for `fbsource//arvr/apps/hsr/demo:client_ipaBinary (cfg:iphoneos-arm64-iphonesimulator-no-san#cbc4c1f0584cf5e6)`
      1: Error running analysis for `fbsource//arvr/apps/hsr/demo:client_ipaBinary (cfg:iphoneos-arm64-iphonesimulator-no-san#cbc4c1f0584cf5e6)`
      2: Error running analysis for `fbsource//fbobjc/Libraries/FBProvider:FBProviderDefines (cfg:iphoneos-arm64-iphonesimulator-no-san#cbc4c1f0584cf5e6)`
      3: Error running analysis for `fbsource//fbobjc/Libraries/FBProvider:FBProviderDefines (cfg:iphoneos-arm64-iphonesimulator-no-san#cbc4c1f0584cf5e6)`
      4: Traceback (most recent call last):
           File <builtin>, in <module>
           * fbcode/buck2/prelude/rules.bzl:104, in buck2_compatibility_shim
               return impl(ctx)
           * fbcode/buck2/prelude/apple/apple_library.bzl:145, in apple_library_impl
               apple_library_validate_for_meta_restrictions(ctx)  # oss-disable
           * fbcode/buck2/prelude/apple/meta_only/apple_library_meta_validation.bzl:90, in apple_library_validate_for_meta_restrictions
               fail("Found `fb_xplat_library()` suffix target violation: `{}` -> `{}`. Most ...
         error: fail: Found `fb_xplat_library()` suffix target violation: `fbsource//fbobjc/Libraries/FBProvider:FBProviderDefines` -> `fbsource//xplat/FBBaseLite:FBBaseLite`. Most of the time, you can fix by adding `Apple` to `fbsource//xplat/FBBaseLite:FBBaseLite` as it appears in the dependencies of `fbsource//fbobjc/Libraries/FBProvider:FBProviderDefines`.
           --> fbcode/buck2/prelude/apple/meta_only/apple_library_meta_validation.bzl:90:13
            |
         90 |             fail("Found `fb_xplat_library()` suffix target violation: `{}` -> `{}`. Most of the time, you can fix by adding `Apple` to `{}` as it appears in the dependencies of `{}`.".format(unconfigured_target, dep_unconfigured_target, dep_unconfigured_target, unconfigured_target))
            |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            |
```

**Solution**

Disable validation for arvr targets which do not use suffixing, as the validation is not appropriate for such targets.

Reviewed By: blackm00n

Differential Revision: D63689556

fbshipit-source-id: c587494fe59f10dd3fcfe53c5db84dac08c608ba