Consistently set RUSTC_BOOTSTRAP when using -Z options
Summary:
`cxx`'s Buck2 CI is broken by {D52537366}.

```
Action failed: root//third-party:unicode-width-0.1.11 (prelude//platforms:default#524f8da68ea2a374) (rustc rlib-pic-static_pic-metadata/unicode_width-metadata rlib,pic,metadata [diag])

error: the option `Z` is only accepted on the nightly compiler

help: consider switching to a nightly toolchain: `rustup default nightly`
note: selecting a toolchain with `+toolchain` arguments require a rustup proxy; see <https://rust-lang.github.io/rustup/concepts/index.html>
note: for more information about Rust's stability policy, see <https://doc.rust-lang.org/book/appendix-07-nightly-rust.html#unstable-features>

error: 1 nightly option were parsed
```

https://github.com/dtolnay/cxx/actions/runs/7668824008/job/20901419639

Reviewed By: diliop

Differential Revision: D53140347

fbshipit-source-id: e2b6d3bbde5112bee950dca0d41fea6e6c05cbe4