Delete -Zsave-analysis subtarget
Summary:
The flag no longer exists.

```
$ RUSTC_BOOTSTRAP=1 rustc +1.68.0 -Zsave-analysis
error: no input filename given
```

```
$ RUSTC_BOOTSTRAP=1 rustc +1.69.0 -Zsave-analysis
error: unknown unstable option: `save-analysis`
```

Reviewed By: zertosh

Differential Revision: D45292993

fbshipit-source-id: 110f46474b635013f260147181f9ff128d9c7085