Split stusbgen and source modifier plugins
Summary:
## Context
Previous approach for standalone stubgen D61202693 doesn't work well as we're seeing some test failure due in D63754817 when enabling the config.

## Problem

Some tests are failing due to `NoClassDefFoundError`

```
java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/facebook/fbui/util/text/caps/GeneratedCapsModule8ac267ee
	at com.facebook.litho.TreeFuture.runAndGet(TreeFuture.kt:375)
```

The `GeneratedCapsModule8ac267ee` class is missing due to we have different ABI in so build.

This is due to there could be some private properties that have UL injections, because these code get stripped, UL won't have a change to collect metadata and hence we will end up having a different module nonce for UL.

The metadata could affect the nonce of the generated module class hence the ABI, even though the injection could be private.

## Solution (This stack)

We're taking the plan B to move source modifier step after KSP.

The major change is source modifier runs together with jvm-abi-gen in main KotlinC step

 {F1949038602}

## This diff
- Create different plugin interface for stubsgen & source_modifier

Reviewed By: nghuiqin

Differential Revision: D64858102

fbshipit-source-id: 54b466d4b34b2116c0e1318f0c95afbd8541c2ce