Set TARGET based on host-tuple
Summary:
Creating a RustToolchainInfo with rustc_target_triple set to None is supposed to perform builds that are equivalent to not passing rustc any `--target` flag. This is the default behavior — build for the host.

https://www.internalfb.com/code/fbsource/[4017120bcfc8ae614890d86080fd4d1d00e0f715]/fbcode/buck2/prelude/rust/rust_toolchain.bzl?lines=38-40

The cargo_buildscript.bzl is one of the few places with a hard dependency on the toolchain info's rustc_target_triple being non-None. If it's None, build scripts were unable to run because of this type error: the env would contain `env["TARGET"] = None`.

```lang=text,counterexample
  * fbcode/buck2/prelude/rust/cargo_buildscript.bzl:139, in _cargo_buildscript_impl
      ctx.actions.run(
error: Type of parameter `env` doesn't match, expected `dict[str, CellPath | CellRoot | OutputArtifact | ProjectRoot | ResolvedStringWithMacros | TaggedCommandLine | TargetLabel | TransitiveSetArgsProjection | WriteJsonCliArgs | artifact | cmd_args | label | str | RunInfo]`, actual `dict (repr: {"CARGO": "/bin/false", "CARGO_PKG<<...>>t.bzl:97:11-56>)})`
   --> fbcode/buck2/prelude/rust/cargo_buildscript.bzl:139:5
    |
139 |       ctx.actions.run(
    |  _____^
140 | |         cmd,
141 | |         env = env,
142 | |         category = "buildscript",
143 | |     )
    | |_____^
    |
```

Having `env["TARGET"]` is an important part of the API for Cargo build scripts. Unlike `--target`, we can't just leave it out in non-cross-compiled builds.

But rustc exposes a way to get the compiler's host tuple, which is the tuple it builds for when not given `--target`.

```lang=text
$ rustc --print=host-tuple
x86_64-unknown-linux-gnu
```

This diff wires that up to be used for `env["TARGET"]` for build scripts when the RustToolchainInfo uses the default None rustc_target_triple.

With some other small upcoming fixes, Buck setups that don't care about cross-compilation (but do want to support native builds on a variety of mainstream platforms) will just be able to use rustc_target_triple=None instead of reproducing this kind of select:

https://www.internalfb.com/code/fbsource/[627f5a6b3d2802201773bd35733ee999ee6ee70a]/fbcode/buck2/prelude/toolchains/rust.bzl?lines=10-34

Reviewed By: JakobDegen

Differential Revision: D72754010

fbshipit-source-id: 8b6d98773530e4e48463b92b13bf48253c75515c