Read pre-dex class names from the DEX, not the input jar
Summary:
Summary by me:

tldr we currently rely on this patch we apply to `DexItemFactory`:
https://www.internalfb.com/code/D8/[agp-8.8.2%3A20b1eb9ebf13a99d97fa86dc330ebf0bd239da2c]/src/main/java/com/android/tools/r8/graph/DexItemFactory.java?lines=3456-3466

which is a guess at the synthetic classes D8 adds during dexing. It looks pretty brittle.

Incidentally, using `-target 11` with javac leads to java bytecode which causes D8 to spit out an `-IA` suffixed class in certain cases, which was lost in the dex merge leading to this runtime crash in WhatsApp:
> java.lang.NoClassDefFoundError: Failed resolution of: Lorg/whispersystems/jobqueue/JobParameters-IA;

So, we can replace this brittle guessing with a solid API D8 already provides: a `DexIndexedConsumer` visitor which notifies of all types.

Reviewed By: NavidQar

Differential Revision: D114768660

fbshipit-source-id: 0df3512cda5908c8c301e8e58e16928bc870bcc0