Escape carriage return in environment variables
Summary:
Without this, we end up with a line like this in metadata-fast-diag.args, currently affecting the enum-assoc crate at version 1.4.0:

```
--env=CARGO_PKG_DESCRIPTION=Procedural macro to associate constants with enum variants.^M\n
```

where `^M` stands for a single ASCII carriage return byte (U+000D) and `\n` is 2 bytes (U+005C; U+006E).

When parsing the flagfile `metadata-fast-diag.args` inside rustc_action.py, Python's `argparse.ArgumentParser(fromfile_prefix_chars="@")` interprets the carriage return as an argument separator, so it perceives the args as:

```
--env=CARGO_PKG_DESCRIPTION=Procedural macro to associate constants with enum variants.
\n
```

Since the `\n` line is the first non-flag line it gets interpreted as the start of rustc_action.py's `parser.add_argument("rustc", nargs=argparse.REMAINDER)`, which leads to `asyncio.create_subprocess_exec` failing like this:

```lang=log,counterexample
Traceback (most recent call last):
  File "/tmp/recli.uLGPgX/buck-out/v2/art/prelude/rust/tools/__rustc_action__/fe125b2ac57ebbb4/__rustc_action__/rustc_action.py", line 467, in <module>
    sys.exit(asyncio.run(main()))
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/fbcode/platform010/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/fbcode/platform010/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/fbcode/platform010/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/tmp/recli.uLGPgX/buck-out/v2/art/prelude/rust/tools/__rustc_action__/fe125b2ac57ebbb4/__rustc_action__/rustc_action.py", line 401, in main
    proc = await asyncio.create_subprocess_exec(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/fbcode/platform010/lib/python3.12/asyncio/subprocess.py", line 224, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/fbcode/platform010/lib/python3.12/asyncio/base_events.py", line 1756, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/fbcode/platform010/lib/python3.12/asyncio/unix_events.py", line 211, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/fbcode/platform010/lib/python3.12/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/local/fbcode/platform010/lib/python3.12/asyncio/unix_events.py", line 820, in _start
    self._proc = subprocess.Popen(
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/fbcode/platform010/lib/python3.12/subprocess.py", line 1028, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/fbcode/platform010/lib/python3.12/subprocess.py", line 1957, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '\\n'
```

Reviewed By: JakobDegen

Differential Revision: D116230948

fbshipit-source-id: b450d94c846566ac4f75c57b7f85f302d16ef146