update apple installer path in apple_rules_impl.bzl
Summary:
Try to fix last WA repo sync failure D63028940

```
Caused by:
    0: From load at buck2/prelude/prelude.bzl:8
    1: From load at buck2/prelude/native.bzl:31
    2: From load at buck2/prelude/rules.bzl:15
    3: From load at buck2/prelude/rules_impl.bzl:10
    4: Error evaluating module: `prelude//apple/apple_rules_impl.bzl`
    5: Traceback (most recent call last):
         * buck2/prelude/apple/apple_rules_impl.bzl:185, in <module>
             "installer": attrs.default_only(attrs.label(default = "buck//src/com/facebook...
       error: Error coercing attribute default
          --> buck2/prelude/apple/apple_rules_impl.bzl:185:41
           |
       185 |         "installer": attrs.default_only(attrs.label(default = "buck//src/com/facebook/buck/installer/apple:apple_installer")),
           |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           |
```

Use same path in D62302956 instead of a buck cell
so this still works in WA repo.

Reviewed By: hick209

Differential Revision: D63044954

fbshipit-source-id: c18c922d5a1005054c3c353ecb799634fabdcf95