Support interpolation in toolchain rustc flags
Summary:
Fixes this error when a RustToolchainInfo uses `attrs.list(attrs.arg())` instead of `attrs.list(attrs.string())` for its value of `rustc_flags`. I hit this in https://github.com/dtolnay/buck2-rustc-bootstrap.

```lang=log,counterexample
error: Object of type `ResolvedStringWithMacros` has no attribute `startswith`
   --> fbcode/buck2/prelude/rust/cargo_buildscript.bzl:160:12
    |
160 |         if flag.startswith("-Copt-level="):
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

`attrs.arg()` shows up inside rule implementations as `ResolvedStringWithMacros` instead of `str`.

Reviewed By: capickett

Differential Revision: D96802872

fbshipit-source-id: 931133a5f1c14708cba1a15ce3bf70ed0143e29e