Support overlaying srcs atop an http_archive
Summary:
```
http_archive(
    name = "fst-0.4.7.crate",
    urls = ["https://crates.io/api/v1/crates/fst/0.4.7/download"],
    sha256 = "7ab85b9b05e3978cc9a9cf8fea7f01b494e1a09ed3037e16ba39edc7a29eb61a",
    strip_prefix = "fst-0.4.7",
)

rust_library(
    name = "fst-0.4.7",
    srcs = [":fst-0.4.7.crate"],
    mapped_srcs = {
        ":fst-0.4.7-build-script-build-srcs[crc32_table.rs]": "fst-0.4.7.crate/src/crc32_table.rs",
    },
    crate = "fst",
    crate_root = "fst-0.4.7.crate/src/lib.rs",
    edition = "2018",
)
```

Previously this would fail. We'd end up with an argument to `ctx.actions.symlinked_dir` that looks like:

```
{
    "fst-0.4.7.crate": ...
    "fst-0.4.7.crate/src/crc32_table.rs": ...
}
```

and there is no way that `symlinked_dir` could accommodate both of those two being symlinks.

```
Error running analysis for `root//third-party:fst-0.4.7 (prelude//platforms:default)`

Caused by:
    Traceback (most recent call last):
      * tools/buck/prelude/rust/rust_library.bzl:165, in <module>
          compile_ctx = compile_context(ctx)
      * tools/buck/prelude/rust/build.bzl:84, in compile_context
          symlinked_srcs = ctx.actions.symlinked_srcs("__srcs", symlinks)
    error: Paths to symlinked_dir must be non-overlapping, but got "fst-0.4.7.crate" and "fst-0.4.7.crate/src/crc32_table.rs"
      --> tools/buck/prelude/rust/build.bzl:84:22
       |
    84 |     symlinked_srcs = ctx.actions.symlinked_dir("__srcs", symlinks)
       |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
```

Reviewed By: krallin

Differential Revision: D45076215

fbshipit-source-id: 0fa06c7ca83ba27947de08c1e9754c0c4793e4b7