Make properties optional for broken builds
Summary:
Turns out not all `apple_bundle` targets have dsyms/linker_maps, etc.

Example failures:
https://www.internalfb.com/sandcastle/job/54043195633245492/artifact/actionlog.54043195808412450.log?selectedLines=201-209-1-1

https://www.internalfb.com/sandcastle/workflow/1288029493440317761/artifact/actionlog.1288029493640203310.stdout.1?selectedLines=170-178-1-1

Sample error:
```
       error: Error accessing dependencies of `fbsource//fbobjc/Apps/Internal/Orchard:Orchard-Finalized (cfg:dev-macos-macosx-no-san#776a91d850aa0779)`
         --> fbcode/buck2/prelude/apple/apple_package.bzl:66:17
          |
       66 |         dsyms = ctx.attrs.bundle[AppleDebuggableInfo].dsyms,
          |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          |
    1: provider collection does not have a key `AppleDebuggableInfo`, available keys are: [`DefaultInfo`, `AppleBundleInfo`]
    2: provider collection does not have a key `AppleDebuggableInfo`, available keys are: [`DefaultInfo`, `AppleBundleInfo`]
```

Able to repro the error with this command:
```
buck2 audit providers --flagfile fbsource//fbobjc/mode/buck2/linux --config "user.macosx_binary_finalize_codesign=true" --config "apple.use_entitlements_when_adhoc_code_signing=true" --config "apple.simulator_webview_js_broken_DO_NOT_USE=true" --config "buck2.log_configured_graph_size=true" --config "user.autograph_property_sign_key=fbmacos-apps-prod" --config "client.id=mobile-push-train" --config "cxx.linker_map_enabled=true" --config "apple.stripped_default=true" --config "facebook-dt#apple.xcode_sdk_version=xcode_26.0.0_17a324" --config "facebook-dt#apple.version=pika-17" --config "xplat.available_platforms=CXX,APPLE" --config "apple.dry_run_code_signing=true" --config "apple.codesign=/usr/bin/true" --config "apple.ipa_compression_level=default" --config "cxx.default_platform=macosx-universal" --config "user.sandcastle_build_mode=production" --config "user.sandcastle_schedule_type=master" --config "apple.fb_bundle_version=842877796" --config "apple.fb_version_name=5.0.0.0.76" --config "apple.fb_version_name_short=5.0" --config "user.platform_flavor=macosx-arm64,macosx-x86_64" //fbobjc/Apps/Internal/Orchard:OrchardPackage
```

Though unclear which of those flags help introduce this issue (checked build mode, universal, etc).

Making these values optional and checking if the providers exist instead of assuming they do. This seems to be unique to Catalyst or MacOSX builds. Will follow up on Monday.

overriding_review_checks_triggers_an_audit_and_retroactive_review
Oncall Short Name: apple_workflows

Differential Revision: D89151848

fbshipit-source-id: 7977153ec7370cab4ec6717b793b80bbf2e5174b