Fix build target pattern parsing
Summary:
Right now, we're parsing `cell//a/b/*` as a valid build target pattern:

`    error: fail: Successfully managed to parse bad build target pattern `cell//a/b/*`:

```
buck2 build fbcode//buck2/tests/targets/rules/utils/bad:build_pattern_test_15

Buck UI: https://www.internalfb.com/buck2/e20084da-059f-4da5-b902-748abd9f9766
Network: Up: 0B  Down: 0B
Jobs completed: 632. Time elapsed: 0.9s.
BUILD FAILED
Error running analysis for `fbcode//buck2/tests/targets/rules/utils/bad:build_pattern_test_15 (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15#dba1b6602d3e247c)`

Caused by:
    Traceback (most recent call last):
      File <builtin>, in <module>
      * fbcode/buck2/tests/targets/rules/utils/defs.bzl:47, in _test_parse_build_target_pattern_fail
          fail("Successfully managed to parse bad build target pattern `{}`: {}".format(
    error: fail: Successfully managed to parse bad build target pattern `cell//a/b/*`: record[BuildTargetPattern](kind=_BuildTargetPatternKind("single"), cell="cell", path="a/b/*", name="*", matches=fbcode/buck2/prelude/utils/build_target_pattern.bzl.matches, as_string=fbcode/buck2/prelude/utils/build_target_pattern.bzl.as_string, _path_with_path_symbol="a/b/*/")
      --> fbcode/buck2/tests/targets/rules/utils/defs.bzl:47:5
       |
    47 |       fail("Successfully managed to parse bad build target pattern `{}`: {}".format(
       |  _____^
    48 | |         ctx.attrs.pattern,
    49 | |         parsed_pattern,
    50 | |     ))
       | |______^
       |
```

Let's use the documented regex and determine that the name is valid.

Note: We probably should rewrite this to test against the regex, but previously when I replaced it with the regex and ran against the test suite, the regex was not correct. For now, just unbreaking the parsing of the name.

Differential Revision: D66125529

fbshipit-source-id: 3ea73455b407e87399c2295fed9daa28ae4e9eb5