Fix type error exposed by dist_lto builds
Summary:
Without this change, we hit type errors when attempting to build iOS apps with distributed thin-LTO. Presumably this code path wasn't exercised previously:

```
error: Value `cmd_args(hidden=[<build artifact out/mobileconfig-usage-check bound to fbsource//fbobjc/Libraries/FBReport:FBProductionReport-mobileconfig-usage-check-gen (fbsource//fbobjc/Apps/Internal/FocusRepresentativeApp:FocusRepresentativeAppDistributedThinLTOPlatform-iphoneos-arm64-production#7e495397de1b95ca)>])` of type `cmd_args` does not match the type annotation `list[typing.Any]` for argument `pre_flags`
```

LinkInfo expects a `list[typing.Any]` and is provided cmd_args directly. Wraps the cmd_args in a list to satisfy the type checker.

Reviewed By: drodriguez

Differential Revision: D57400220

fbshipit-source-id: 45a455c1c261f3ffc2fdc4e3bd443dd0dc79ba74