Add MacCatalyst to MobileCoreServices supported SDKs
Summary:
This is supported from MacCatalyst 14.0 on: https://developer.apple.com/documentation/uniformtypeidentifiers

When building the Internal Catalust app:
```
chatatap@chatatap-mac ~/fbsource (default) [3]> buck2 build fbsource//fbobjc/mode/workchat-catalyst -c cxx.default_platform=maccatalyst-x86_64 //fbobjc/Apps/AtWorkMessenger:AtWorkMessenger-dmg
Buck UI: https://www.internalfb.com/buck2/5c8c5ea4-874d-4d33-a531-0efd002f764e
Note:    Using experimental modern dice
Jobs completed: 3. Time elapsed: 0.0s.
BUILD FAILED
Error running analysis for `fbsource//fbobjc/Apps/AtWorkMessenger:AtWorkMessenger-dmg (fbsource//fbobjc/Apps/AtWorkMessenger/Platforms:AtWorkMessengerCatalyst-maccatalyst-x86_64-local#be8a9aee662efc88)`

Caused by:
    0: Error running analysis for `fbsource//fbobjc/Apps/AtWorkMessenger:AtWorkMessenger-dmgBinary (fbsource//fbobjc/Apps/AtWorkMessenger/Platforms:AtWorkMessengerCatalyst-maccatalyst-x86_64-local#be8a9aee662efc88)`
    1: Error running analysis for `fbsource//fbobjc/Apps/AtWorkMessenger/Libraries/WPMReorderChatsWithinThreadFolderIntentHandler:WPMReorderChatsWithinThreadFolderIntentHandler (fbsource//fbobjc/Apps/AtWorkMessenger/Platforms:AtWorkMessengerCatalyst-maccatalyst-x86_64-local#be8a9aee662efc88)`
    2: Error running analysis for `fbsource//fbobjc/Apps/AtWorkMessenger/Libraries/WPMDraftsKit:WPMDraftsKit (fbsource//fbobjc/Apps/AtWorkMessenger/Platforms:AtWorkMessengerCatalyst-maccatalyst-x86_64-local#be8a9aee662efc88)`
    3: Error running analysis for `fbsource//fbobjc/Libraries/Lexical:Lexical (fbsource//fbobjc/Apps/AtWorkMessenger/Platforms:AtWorkMessengerCatalyst-maccatalyst-x86_64-local#be8a9aee662efc88)`
    4: Traceback (most recent call last):
         File <builtin>, in <module>
         * fbcode/buck2/prelude/apple/apple_library.bzl:134, in apple_library_impl
             return get_apple_library_providers([])
         * fbcode/buck2/prelude/apple/apple_library.bzl:128, in get_apple_library_providers
             output = cxx_library_parameterized(ctx, constructor_params)
         * fbcode/buck2/prelude/cxx/cxx_library.bzl:464, in cxx_library_parameterized
             dep_infos, link_group_map, link_execution_preference = _get_shared_library_li...
         * fbcode/buck2/prelude/cxx/cxx_library.bzl:1138, in _get_shared_library_links
             return apple_build_link_args_with_deduped_flags(
         * fbcode/buck2/prelude/apple/apple_frameworks.bzl:137, in apple_build_link_args_with_deduped_flags
             link_info = _apple_link_info_from_linkables(
         * fbcode/buck2/prelude/apple/apple_frameworks.bzl:192, in _apple_link_info_from_linkables
             framework_link_args = _get_apple_frameworks_linker_flags(ctx, merge_framework...
         * fbcode/buck2/prelude/apple/apple_frameworks.bzl:50, in _get_apple_frameworks_linker_flags
             flags.add(get_framework_linker_args(ctx, linkable.framework_names))
         * fbcode/buck2/prelude/apple/apple_framework_versions.bzl:1040, in get_framework_linker_args
             fail("SDK framework {} is not compatible with platform {}".format(name, sdk_n...
       error: fail: SDK framework MobileCoreServices is not compatible with platform maccatalyst
           --> fbcode/buck2/prelude/apple/apple_framework_versions.bzl:1040:17
            |
       1040 |                 fail("SDK framework {} is not compatible with platform {}".format(name, sdk_name))
            |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            |
```

Reviewed By: rmaz

Differential Revision: D53141459

fbshipit-source-id: 6405ac5e5decc17233337b38023b49408af7569a