Fix type error when using rustdoc test in OSS
Summary:
```
Error running analysis for `root//:cxx (prelude//platforms:default#524f8da68ea2a374)`: Traceback (most recent call last):
  File <builtin>, in <module>
  * tools/buck/prelude/rust/rust_library.bzl:248, in rust_library_impl
      rustdoc_test = generate_rustdoc_test(
  * tools/buck/prelude/rust/build.bzl:291, in generate_rustdoc_test
      return _long_command(
error: Value `rustdoc` of type `string` does not match the type annotation `"RunInfo"` for argument `exe`
   --> tools/buck/prelude/rust/build.bzl:291:12
    |
291 |       return _long_command(
    |  ____________^
292 | |         ctx = ctx,
293 | |         exe = toolchain_info.rustdoc,
294 | |         args = rustdoc_cmd,
295 | |         argfile_name = "{}.args".format(common_args.subdir),
296 | |     )
    | |_____^
    |
```

Using `RunInfo` matches the type we use in FB's internal production `RustToolchainInfo` (because those have a hermetic Rust toolchain checked into the monorepo, which is accessed as an exec_dep of the toolchain), so it is guaranteed to be better exercised.

Reviewed By: zertosh

Differential Revision: D47708235

fbshipit-source-id: fe52b6a7c6f9a909e011bdc556e73a213ffa9508